# Generated by Django 5.2.4 on 2025-07-30 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptIQ', '0002_kidmode_quizsession_useranswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('movement_warnings', models.IntegerField(default=0)),
                ('max_warnings', models.IntegerField(default=2)),
                ('is_cheating_detected', models.BooleanField(default=False)),
                ('camera_feed_active', models.BooleanField(default=False)),
                ('warning_history', models.JSONField(default=list)),
                ('quiz_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdaptIQ.quizsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
